export const REMINDER = "ADMIN_REMINDER";
export const SHIFT_ASSIGNMENT = "SHIFT_ASSIGNMENT";
export const SHIFT_PICKUP = "SHIFT_PICKUP";
export const MESSAGE_NOTIFICATIONS = "MESSAGE_NOTIFICATIONS";
export const NEWS_ALERT = "NEWS_ALERT";
export const CLOCK_OUT_ALERT = "CLOCK_OUT_ALERT";
export const SUPPORT_TICKET = "SUPPORT_TICKET";
export const SHIFT_REQUEST = "SHIFT_REQUEST";

// INSTACARE
export const FACILITY_CANCELLATION = "FACILITY_CANCELLATION";
export const EMPLOYEE_CALLOFF = "EMPLOYEE_CALLOFF";
export const EMPLOYEE_LATE = "EMPLOYEE_LATE";

export const FAILURE_CLOCKIN = "Failure to Clock In.";
export const FAILURE_CLOCKOUT = "Failure to Clock Out.";

export const EMPLOYEE_EARLY = "EMPLOYEE_EARLY";
export const NO_CALL_NO_SHOW = "NO_CALL_NO_SHOW";
export const ADD_SHIFT = "ADD_SHIFT";
export const TIMECARD_FLAG = "TIMECARD_FLAG";

export const PEOPLE_UPDATED = "PEOPLE_UPDATED";

// export const SHIFT_ASSIGNMENT = "SHIFT_ASSIGNMENT";
// Timecard less than 5 Hours
// Employee Not Clocked In /Out
export const SHIFT_CONFIRMATION = "SHIFT_CONFIRMATION";
export const SHIFT_DELETED = "SHIFT_DELETED";
export const SHIFT_EDIT = "SHIFT_EDIT";
export const EDIT_PROFILE = "ADD_SHIFT";

// FACILITY
// export const FACILITY_CANCELLATION = "FACILITY_CANCELLATION";
// export const EMPLOYEE_CALLOFF = "EMPLOYEE_CALLOFF";
// export const EMPLOYEE_LATE = "EMPLOYEE_LATE";
// export const NO_CALL_NO_SHOW = "NO_CALL_NO_SHOW";
// export const SHIFT_ASSIGNMENT = "SHIFT_ASSIGNMENT";
// export const ADD_SHIFT = "ADD_SHIFT";
// export const SHIFT_CONFIRMATION = "SHIFT_CONFIRMATION";
// export const SHIFT_DELETED = "SHIFT_DELETED";
// export const SHIFT_EDIT = "SHIFT_EDIT";

// EMPLOYEE
// export const FACILITY_CANCELLATION = "FACILITY_CANCELLATION";
// export const EMPLOYEE_CALLOFF = "EMPLOYEE_CALLOFF";
// Timecard less than 5 Hours
// Employee Not Clocked In /Out
// export const NO_CALL_NO_SHOW = "NO_CALL_NO_SHOW";
// export const ADD_SHIFT = "ADD_SHIFT";
// export const SHIFT_CONFIRMATION = "SHIFT_CONFIRMATION";
export const SHIFT_REMINDER_12HR = "SHIFT_REMINDER_12HR";
// export const EDIT_PROFILE = "ADD_SHIFT";

export const IMPORTANT_NOTIFICATIONS_INSTACARE = [
  FACILITY_CANCELLATION,
  EMPLOYEE_CALLOFF,
  NO_CALL_NO_SHOW,
  SHIFT_REQUEST,
  TIMECARD_FLAG,
  PEOPLE_UPDATED,
  EMPLOYEE_LATE,
  EMPLOYEE_EARLY,
  FAILURE_CLOCKIN,
  FAILURE_CLOCKOUT,
  SUPPORT_TICKET,
];

export const IMPORTANT_NOTIFICATIONS_FACILITY = [
  EMPLOYEE_CALLOFF,
  NO_CALL_NO_SHOW,
  SHIFT_REQUEST,
  SHIFT_ASSIGNMENT,
  SHIFT_PICKUP,
  SHIFT_CONFIRMATION,
  EMPLOYEE_LATE,
  EMPLOYEE_EARLY,
];

export const IMPORTANT_NOTIFICATIONS_EMPLOYEE = [
  FACILITY_CANCELLATION,
  NO_CALL_NO_SHOW,
  SHIFT_ASSIGNMENT,
  SHIFT_PICKUP,
  SHIFT_CONFIRMATION,
  SHIFT_REMINDER_12HR,
  FAILURE_CLOCKIN,
  FAILURE_CLOCKOUT,
];

export const IMPORTANT_NOTIFICATIONS = [
  SHIFT_ASSIGNMENT,
  SHIFT_PICKUP,
  CLOCK_OUT_ALERT,
  SUPPORT_TICKET,
  SHIFT_REQUEST,
  TIMECARD_FLAG,
];

export const NotificationTypeMap = {
  ADMIN_REMINDER: "Reminder from InstaCare",
  SHIFT_ASSIGNMENT: "Shift Assignment from InstaCare",
  MESSAGE_NOTIFICATIONS: "Message notification",
  NEWS_ALERT: "News Alert",
  CLOCK_OUT_ALERT: "You clocked out of a shift",
  SUPPORT_TICKET: "Support ticket raised",
  SHIFT_REQUEST: "You have a new shift request",
};
