export const shiftTemplate = {
  numOfPositions: null,
  facilityID: null,
  shiftStart: null,
  shiftEnd: null,
  date: null,
  roleRequired: null,
  rate: null,
  floorNumber: null,
  supervisor: null,
  incentives: {
    incentiveBy: null,
    incentiveType: null,
    incentiveAmount: null,
    notes: null,
  },
  cancellationGuarantee: false,
  isAssigned: false,
  isIncentive: false,
  isGuarantee: false,
  isLate: false,
  isCallOff: false,
  isSelected: false,
  recurringSchedule: null,
};
