/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { IconProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type SidemenuOverridesProps = {
    "8"?: PrimitiveOverrideProps<TextProps>;
    Sidemenu?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 4"?: PrimitiveOverrideProps<ViewProps>;
    "Group 5"?: PrimitiveOverrideProps<ViewProps>;
    side_menu_item4330?: PrimitiveOverrideProps<ViewProps>;
    grid?: PrimitiveOverrideProps<ViewProps>;
    Vector4334?: PrimitiveOverrideProps<IconProps>;
    Vector4335?: PrimitiveOverrideProps<IconProps>;
    Vector4336?: PrimitiveOverrideProps<IconProps>;
    Vector4337?: PrimitiveOverrideProps<IconProps>;
    Dashboard4338?: PrimitiveOverrideProps<TextProps>;
    side_menu_item4339?: PrimitiveOverrideProps<ViewProps>;
    calendar?: PrimitiveOverrideProps<ViewProps>;
    Vector4341?: PrimitiveOverrideProps<IconProps>;
    Vector4342?: PrimitiveOverrideProps<IconProps>;
    Vector4343?: PrimitiveOverrideProps<IconProps>;
    Vector4344?: PrimitiveOverrideProps<IconProps>;
    Dashboard4345?: PrimitiveOverrideProps<TextProps>;
    side_menu_item4346?: PrimitiveOverrideProps<ViewProps>;
    Dashboard4347?: PrimitiveOverrideProps<TextProps>;
    user?: PrimitiveOverrideProps<ViewProps>;
    Vector4349?: PrimitiveOverrideProps<IconProps>;
    Vector4350?: PrimitiveOverrideProps<IconProps>;
    side_menu_item4351?: PrimitiveOverrideProps<ViewProps>;
    Dashboard4352?: PrimitiveOverrideProps<TextProps>;
    users?: PrimitiveOverrideProps<ViewProps>;
    Vector4354?: PrimitiveOverrideProps<IconProps>;
    Vector4355?: PrimitiveOverrideProps<IconProps>;
    Vector4356?: PrimitiveOverrideProps<IconProps>;
    Vector4357?: PrimitiveOverrideProps<IconProps>;
    side_menu_item4358?: PrimitiveOverrideProps<ViewProps>;
    Dashboard4359?: PrimitiveOverrideProps<TextProps>;
    radio?: PrimitiveOverrideProps<ViewProps>;
    Vector4361?: PrimitiveOverrideProps<IconProps>;
    Vector4362?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 33"?: PrimitiveOverrideProps<IconProps>;
    side_menu_item4365?: PrimitiveOverrideProps<ViewProps>;
    Dashboard4366?: PrimitiveOverrideProps<TextProps>;
    clock?: PrimitiveOverrideProps<ViewProps>;
    Vector4368?: PrimitiveOverrideProps<IconProps>;
    Vector4369?: PrimitiveOverrideProps<IconProps>;
    side_menu_item4370?: PrimitiveOverrideProps<ViewProps>;
    Dashboard4371?: PrimitiveOverrideProps<TextProps>;
    "user-check"?: PrimitiveOverrideProps<ViewProps>;
    Vector4373?: PrimitiveOverrideProps<IconProps>;
    Vector4374?: PrimitiveOverrideProps<IconProps>;
    Vector4375?: PrimitiveOverrideProps<IconProps>;
    side_menu_item4376?: PrimitiveOverrideProps<ViewProps>;
    "Total Billing"?: PrimitiveOverrideProps<TextProps>;
    "file-text"?: PrimitiveOverrideProps<ViewProps>;
    Vector4379?: PrimitiveOverrideProps<IconProps>;
    Vector4380?: PrimitiveOverrideProps<IconProps>;
    Vector4381?: PrimitiveOverrideProps<IconProps>;
    Vector4382?: PrimitiveOverrideProps<IconProps>;
    Vector4383?: PrimitiveOverrideProps<IconProps>;
    side_menu_item4385?: PrimitiveOverrideProps<ViewProps>;
    Dashboard4386?: PrimitiveOverrideProps<TextProps>;
    "help-circle"?: PrimitiveOverrideProps<ViewProps>;
    Vector4388?: PrimitiveOverrideProps<IconProps>;
    Vector4389?: PrimitiveOverrideProps<IconProps>;
    Vector4390?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 3"?: PrimitiveOverrideProps<IconProps>;
    "Jessi Narway"?: PrimitiveOverrideProps<TextProps>;
    RN?: PrimitiveOverrideProps<TextProps>;
    "Line 1"?: PrimitiveOverrideProps<IconProps>;
    side_menu_item4395?: PrimitiveOverrideProps<ViewProps>;
    Logout?: PrimitiveOverrideProps<TextProps>;
    power?: PrimitiveOverrideProps<ViewProps>;
    Vector4398?: PrimitiveOverrideProps<IconProps>;
    Vector4399?: PrimitiveOverrideProps<IconProps>;
    "Line 2"?: PrimitiveOverrideProps<IconProps>;
    x?: PrimitiveOverrideProps<ViewProps>;
    Vector4402?: PrimitiveOverrideProps<IconProps>;
    Vector4403?: PrimitiveOverrideProps<IconProps>;
    "Group 7"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 7"?: PrimitiveOverrideProps<ViewProps>;
    "edit-2"?: PrimitiveOverrideProps<ViewProps>;
    Vector4407?: PrimitiveOverrideProps<IconProps>;
    "Group 269"?: PrimitiveOverrideProps<ViewProps>;
    "Status: Available"?: PrimitiveOverrideProps<TextProps>;
    "chevron-down"?: PrimitiveOverrideProps<ViewProps>;
    Vector4411?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 34"?: PrimitiveOverrideProps<IconProps>;
} & EscapeHatchProps;
export declare type SidemenuProps = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: SidemenuOverridesProps | undefined | null;
}>;
export default function Sidemenu(props: SidemenuProps): React.ReactElement;
